### ISSUE TITLE
Unable to pass mock SQSClient to property typed as SQSClient

### ISSUE THREAD

**Issue by dmeehan1968** [m-radzikowski/aws-sdk-client-mock#233] opened 2024-07-13 12:00 UTC
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Relates to #197 

I've tried all of the suggestions here but the reported type problem is always the same.

<img width="892" alt="Screenshot 2024-07-13 at 12 45 28" src="https://github.com/user-attachments/assets/cd589bcd-dfc6-4aa6-a81a-e2a6beaab20d">

I can workaround the problem using the `as unknown as SQSCLient` override.

Note that there is a conflict for @smithy/types in @aws-lambda-powertools/tracer, but even when following the steps in #197, removing the dependency or creating an override didn't resolve the issue.

I use Jetbrains PHPStorm 2024.2 EAP as my IDE.

### Reproduction

```ts
const mockSqsClient = mockClient(SQSClient)
const client: SQSClient = mockSqsClient
```

### Environment

- Node version: v20.15.1
- Testing lib and version: 

```
    "@types/jest": "^29.5.12",
    "jest": "^29.7.0",
    "jest-mock-extended": "^3.0.7",
    "ts-jest": "^29.2.2",
    "ts-node": "^10.9.2",
```

- Typescript version: 5.5.3
- AWS SDK v3 Client mock version:

```
    "aws-sdk-client-mock": "^4.0.1",
    "aws-sdk-client-mock-jest": "^4.0.1",
```

- AWS JS SDK libs and versions:

```
    "@aws-cdk/aws-iot-actions-alpha": "^2.148.1-alpha.0",
    "@aws-cdk/aws-iot-alpha": "^2.148.1-alpha.0",
    "@aws-lambda-powertools/logger": "^2.4.0",
    "@aws-lambda-powertools/metrics": "^2.4.0",
    "@aws-lambda-powertools/tracer": "^2.4.0",
    "@aws-sdk/client-dynamodb": "^3.614.0",
    "@aws-sdk/client-eventbridge": "^3.614.0",
    "@aws-sdk/client-sqs": "^3.614.0",
    "@aws-sdk/client-timestream-query": "^3.614.0",
    "@aws-sdk/client-timestream-write": "^3.614.0",
    "@aws-sdk/lib-dynamodb": "^3.614.0",
    "@middy/core": "^5.4.3",
    "@types/aws-lambda": "^8.10.141",
    "aws-cdk-lib": "^2.148.1",
```

- @smithy/types

```
├─┬ @aws-lambda-powertools/tracer@2.4.0
│ └─┬ aws-xray-sdk-core@3.9.0
│   └─┬ @smithy/service-error-classification@2.1.5
│     └── @smithy/types@2.12.0
├─┬ @aws-sdk/client-dynamodb@3.614.0
│ ├─┬ @aws-sdk/client-sso-oidc@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/client-sts@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/core@3.614.0
│ │ ├─┬ @smithy/signature-v4@3.1.2
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/credential-provider-node@3.614.0
│ │ ├─┬ @aws-sdk/credential-provider-env@3.609.0
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @aws-sdk/credential-provider-http@3.614.0
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @aws-sdk/credential-provider-ini@3.614.0
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @aws-sdk/credential-provider-process@3.614.0
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @aws-sdk/credential-provider-sso@3.614.0
│ │ │ ├─┬ @aws-sdk/client-sso@3.614.0
│ │ │ │ └── @smithy/types@3.3.0 deduped
│ │ │ ├─┬ @aws-sdk/token-providers@3.614.0
│ │ │ │ └── @smithy/types@3.3.0 deduped
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @aws-sdk/credential-provider-web-identity@3.609.0
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @smithy/credential-provider-imds@3.1.4
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @smithy/property-provider@3.1.3
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ ├─┬ @smithy/shared-ini-file-loader@3.1.4
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/middleware-endpoint-discovery@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/middleware-host-header@3.609.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/middleware-logger@3.609.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/middleware-recursion-detection@3.609.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/middleware-user-agent@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/region-config-resolver@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/types@3.609.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/util-endpoints@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/util-user-agent-browser@3.609.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/util-user-agent-node@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/config-resolver@3.0.5
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/core@2.2.6
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/fetch-http-handler@3.2.1
│ │ ├─┬ @smithy/querystring-builder@3.0.3
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/hash-node@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/invalid-dependency@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/middleware-content-length@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/middleware-endpoint@3.0.5
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/middleware-retry@3.0.9
│ │ ├─┬ @smithy/service-error-classification@3.0.3
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/middleware-serde@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/middleware-stack@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/node-config-provider@3.1.4
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/node-http-handler@3.1.2
│ │ ├─┬ @smithy/abort-controller@3.1.1
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/protocol-http@4.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/smithy-client@3.1.7
│ │ ├── @smithy/types@3.3.0 deduped
│ │ └─┬ @smithy/util-stream@3.0.6
│ │   └── @smithy/types@3.3.0 deduped
│ ├── @smithy/types@3.3.0
│ ├─┬ @smithy/url-parser@3.0.3
│ │ ├─┬ @smithy/querystring-parser@3.0.3
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/util-defaults-mode-browser@3.0.9
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/util-defaults-mode-node@3.0.9
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/util-endpoints@2.0.5
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/util-middleware@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/util-retry@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ └─┬ @smithy/util-waiter@3.1.2
│   └── @smithy/types@3.3.0 deduped
├─┬ @aws-sdk/client-eventbridge@3.614.0
│ ├─┬ @aws-sdk/middleware-signing@3.609.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @aws-sdk/signature-v4-multi-region@3.614.0
│ │ ├─┬ @aws-sdk/middleware-sdk-s3@3.614.0
│ │ │ └── @smithy/types@3.3.0 deduped
│ │ └── @smithy/types@3.3.0 deduped
│ └── @smithy/types@3.3.0 deduped
├─┬ @aws-sdk/client-sqs@3.614.0
│ ├─┬ @aws-sdk/middleware-sdk-sqs@3.614.0
│ │ └── @smithy/types@3.3.0 deduped
│ ├─┬ @smithy/md5-js@3.0.3
│ │ └── @smithy/types@3.3.0 deduped
│ └── @smithy/types@3.3.0 deduped
├─┬ @aws-sdk/client-timestream-query@3.614.0
│ └── @smithy/types@3.3.0 deduped
├─┬ @aws-sdk/client-timestream-write@3.614.0
│ └── @smithy/types@3.3.0 deduped
└─┬ @aws-sdk/lib-dynamodb@3.614.0
  └── @smithy/types@3.3.0 deduped
```

**Comment by pappnase99** [comment] 2024-09-12 16:07
Facing a similar issue, I'm basically trying to do something like this:

```
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
import { mockClient } from 'aws-sdk-client-mock';

let dynamoDbDocumentClient: DynamoDBDocumentClient;
dynamoDbDocumentClient = mockClient(DynamoDBDocumentClient);
```
And I get the error `Type 'AwsStub<ServiceInputTypes, ServiceOutputTypes, DynamoDBDocumentClientResolvedConfig>' is missing the following properties from type 'DynamoDBDocumentClient': config, destroy, middlewareStack`

Dependencies:
```
"@aws-sdk/lib-dynamodb": "^3.650.0",
"aws-sdk-client-mock": "^4.0.1",
```
npm ls shows ` @smithy/types@3.4.0`

**Comment by m-radzikowski** [comment] 2024-09-23 13:45
The issue seems to be gone with the latest SDK libs. With `@smithy/types` v3.4.2 it works with both SDK packages v3.614.0 and v3.654.0 (latest). Please try updating `@aws-sdk/*` packages to the latest and verify all packages use the same version and all use `@smithy/types` v3.4.2 (or force it by adding it as dependency).

I'm closing it, but if problem remains please create a small repo with reproduction where I can run `npm install` and `tsc` to get the error.

**Closed by m-radzikowski** 2024-09-23 13:45 UTC
Labels: bug

**Comment by pappnase99** [comment] 2024-09-23 15:43
Unfortunately I can still reproduce it with the DynamoDBDocumentClient. I've created a small reproduction repo for it, please see https://github.com/pappnase99/client-mock-demo

**Comment by m-radzikowski** [comment] 2024-09-23 16:10
Ok, I see the problem. I misread the issue.

The `mockClient()` function does not return an AWS SDK Client instance. Instead, it's a controller for the mock behavior.

```ts
const sqsMock = mockClient(SQSClient); // type: AwsClientStub<SQSClient>
const sqsClient = new SQSClient(); // type: SQSClient
```

Normally, the `sqsClient` is created in the "production" code (system under test), and the `sqsMock` is created in unit tests to control the `sqsClient` behavior.

You don't need to pass a specific Client instance to the `mockClient()`, by passing the class name you control any Client.

**Comment by pappnase99** [comment] 2024-09-23 16:54
Ok thanks, I think I got it now. But then isn't this part in your Readme under **Mock** a bit misleading?
```
const snsMock = mockClient(SNSClient);

const dynamoDB = new DynamoDBClient({});
const dynamoDBMock = mockClient(dynamoDB);
```

Because in the lower part this implies you create a Mock from the instance named 'dynamoDB'.
